### PR TITLE
Added Wink

### PR DESCRIPTION
**Pull request by danodemano**

### CODE REVIEW

**Comment by danodemano** [comment]
Hope I did that right.  I've never added a pull request to a repo before.

**Comment by pfalcon** [comment]
Thanks for the pull request! But what's the notability of Wink re: the focus of this list (which is openness, or at least letting users maintain enough level of control of the device)? How popular it is? Does it let users write and run custom apps on it? Is API for it is published? Can it run without a cloud?

**Comment by danodemano** [comment]
I dunno, you had SmartThings there.  It's pretty much in the same class.  Some Internet dependency but a large user-base and easy to use.  They also have a well-documented API: https://winkapiv2.docs.apiary.io/

**Comment by pfalcon** [comment]
Sounds good, thanks, merged in deb9669971e371ea4445b70c9df2404d38eb0996

**Pull request closed without merging**
